---
title: "CUNY 618"
subtitle: "HW Assignment - Week 12"
author: "mehtablocker"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---

<style type="text/css">
h3 {
  color: DarkBlue;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

###10.1

```{r ex_10_1}

s <- 100
k <- 105
r <- 0.08
t <- 0.5
div <- 0

u <- 1.3
d <- 0.8
n <- 1
h <- t/n

### a
type <- "call"
c_u <- ifelse(type=="call", max(s*u-k, 0), max(k-s*u, 0))
c_d <- ifelse(type=="call", max(s*d-k, 0), max(k-s*d, 0))
delta <- exp(-1* div * h) * (c_u - c_d) / (s * (u-d))
B <- exp(-1 * r * h) * (u * c_d - d * c_u) / (u - d)
price <- delta * s + B

print(c(price, delta, B))

### b
type <- "put"
c_u <- ifelse(type=="call", max(s*u-k, 0), max(k-s*u, 0))
c_d <- ifelse(type=="call", max(s*d-k, 0), max(k-s*d, 0))
delta <- exp(-1* div * h) * (c_u - c_d) / (s * (u-d))
B <- exp(-1 * r * h) * (u * c_d - d * c_u) / (u - d)
price <- delta * s + B

print(c(price, delta, B))
```

###10.4

```{r ex_10_4}

library(dplyr)
library(tibble)
library(quantmod)
library(knitr)
library(derivmkts)

ticker <- "SPY"
stock_data <- getSymbols(ticker, auto.assign=F, from=Sys.Date()-365*5, warnings=F) %>% as.data.frame()
names(stock_data) <- names(stock_data) %>% gsub(paste0(ticker, "\\."), "", .)
stock_data <- stock_data %>% rownames_to_column(var="Date") %>% mutate(Date=as.Date(Date)) %>% 
  arrange(desc(Date)) %>% mutate(Adjusted_prev = lead(Adjusted, 1), daily_move = log(Adjusted/Adjusted_prev))
stock_data %>% head() %>% kable()

calc_vol <- function(daily_pct_moves){
  sqrt(mean(daily_pct_moves^2, na.rm=T))*sqrt(252)
}

split_vector <- function(vec, n){
  split(vec, ceiling(seq_along(vec)/n))
}

### 1.
calc_vol(stock_data$daily_move)

### 2.
lapply(split_vector(stock_data$daily_move, 252), calc_vol)

### 3.
lapply(split_vector(stock_data$daily_move, 126), calc_vol)

```

###11.1

```{r ex_11_1}

s <- 100
r <- 0
t <- 1
n <- 1
h <- t/n
div <- 0.08
sigma <- 0.3

### a
binomopt(s, k=70, sigma, r, t, div, nstep = 1, american = T, putopt = F)
binomopt(s, k=80, sigma, r, t, div, nstep = 1, american = T, putopt = F)
binomopt(s, k=90, sigma, r, t, div, nstep = 1, american = T, putopt = F)
binomopt(s, k=100, sigma, r, t, div, nstep = 1, american = T, putopt = F)

# Early exercise is beneficial for the 70 and 80 strikes, but not the 90 and 100 strikes

### b
# Early exercise is not beneficial at the higher strikes because there is still time premium left on the option.
```

###12.3

```{r ex_12_3}

s <- 100
k <- 120
sigma <- 0.3
r <- 0.08
div <- 0

bscall(s, k, sigma, r, 1, div)

callperpetual(s, k, sigma, r, div)

```

###13.3

```{r ex_13_3}

s <- 40
sigma <- 0.3
r <- 0.08
div <- 0

# Net delta
net_delta <- greeks(bscall(s, 40, sigma, r, 91/365, div))["Delta",] - greeks(bscall(s, 45, sigma, r, 91/365, div))["Delta",]
net_delta
# So you need to sell about 30 shares of the underlying for every call spread you purchase

# Overnight profit

### At $39
long_call_pnl <- bscall(39, 40, sigma, r, 90/365, div) - bscall(40, 40, sigma, r, 91/365, div)
short_call_pnl <- bscall(40, 45, sigma, r, 91/365, div) - bscall(39, 45, sigma, r, 90/365, div)
stock_pnl <- (40-39) * net_delta
total_pnl <- long_call_pnl + short_call_pnl + stock_pnl
total_pnl

### At $40.5
long_call_pnl <- bscall(40.5, 40, sigma, r, 90/365, div) - bscall(40, 40, sigma, r, 91/365, div)
short_call_pnl <- bscall(40, 45, sigma, r, 91/365, div) - bscall(40.5, 45, sigma, r, 90/365, div)
stock_pnl <- (40-40.5) * net_delta
total_pnl <- long_call_pnl + short_call_pnl + stock_pnl
total_pnl

```


###18.2

```{r ex_18_2}

c(-1.7, 0.55, -0.3, -0.02, 0.85) * 5 + 0.8

```